Wake-up-together-TogetUp/togetup-server

- build.gradle
- src/main/java/com/wakeUpTogetUp/togetUp/WebSecurityConfig.java
- src/main/java/com/wakeUpTogetUp/togetUp/users/UserService.java
- src/main/java/com/wakeUpTogetUp/togetUp/users/model/UserEntity.java
- web security config
- BCryptPasswordEncoder Bean 추가
- UserEntity
- `@PrePersist` 메소드 주석처리
- UserService
- `@Value("${jwt.secret-key}")` 가 없어 실행이 되지 않아 주석 처리함
- 추후 추가 요망
> 전반적인 버그 수정

- src/main/java/com/wakeUpTogetUp/togetUp/config/BaseException.java
- src/main/java/com/wakeUpTogetUp/togetUp/config/BaseResponse.java
- src/main/java/com/wakeUpTogetUp/togetUp/config/BaseResponseStatus.java
- src/main/java/com/wakeUpTogetUp/togetUp/config/GlobalExceptionHandler.java
- src/main/java/com/wakeUpTogetUp/togetUp/files/FileController.java
- src/main/java/com/wakeUpTogetUp/togetUp/files/FileService.java
- BaseResponse
- BaseException
- BaseResponseStatus
- GlobalExceptionHandler
- 그에 따른 fileController, fileService 수정
> <refactor>: 기본응답, 예외, 상태코드 수정

- src/main/java/com/wakeUpTogetUp/togetUp/alarms/AlarmController.java
- src/main/java/com/wakeUpTogetUp/togetUp/alarms/AlarmProvider.java
- src/main/java/com/wakeUpTogetUp/togetUp/alarms/AlarmRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/alarms/AlarmService.java
- src/main/java/com/wakeUpTogetUp/togetUp/alarms/dto/request/AlarmReq.java
- src/main/java/com/wakeUpTogetUp/togetUp/alarms/model/Alarm.java
- src/main/java/com/wakeUpTogetUp/togetUp/routines/RoutineController.java
- src/main/java/com/wakeUpTogetUp/togetUp/routines/RoutineProvider.java
- src/main/java/com/wakeUpTogetUp/togetUp/routines/RoutineRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/routines/RoutineService.java
- src/main/java/com/wakeUpTogetUp/togetUp/routines/dto/request/RoutineReq.java
- src/main/java/com/wakeUpTogetUp/togetUp/routines/model/Routine.java
- src/main/java/com/wakeUpTogetUp/togetUp/utils/mappers/RoutineMapper.java
> Feature : alarm

- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmProvider.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/ObjectDetectionService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/Letterbox.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/ODResult.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/ObjectDetectionModel.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/FcmService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationProvider.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/PushLogService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/dto/request/PushNotificationReq.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/dto/response/NotificationRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/dto/response/PushNotificationRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/entity/Notification.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserService.java
- src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
- src/main/java/com/wakeUpTogetUp/togetUp/config/OpenApiConfig.java
- src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
- src/main/resources/migration/togetup-erd.sql
- default 값 문법 에러 수정
- fcmNotification -> notification
- INVALID_USER_ID -> USER_NOT_FOUND
- ObjectDetection을 mission package에 포함
> #23 [CHORE] 리뷰 반영 및 기타 수정사항

- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomUserRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/model/Room.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/model/RoomUser.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserService.java
- 유저탈퇴 api 작업 하였습니다.
- 유저 탈퇴시 알람, 인원이 0인 그룹, 노티 로그등을 삭제할까말까 고민입니다. (roomUser는 삭제해야하지만)
- 저는삭제를 안해도 괜찮을 것 같은데 의견남겨주세요!
* 삭제를 한다면 장점이 db용량이 늘어난다는 것..?
> #31 [FEAT] : 유저 탈퇴 API

- src/main/java/com/wakeUpTogetUp/togetUp/api/auth/apple/AppleClaimsValidator.java
> [CHORE] : 애플 id-token 검증 변수 변경

- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmProvider.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/PatchAlarmReq.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/PostAlarmReq.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/response/GetAlarmRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/auth/AuthUserResolver.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionObjectRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionProvider.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/response/GetMissionObjectRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/response/GetMissionWithObjectListRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/Mission.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/MissionObject.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/objectDetection/ObjectDetectionService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/request/RoomReq.java
- src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
- src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
- src/main/resources/migration/data.sql
- src/main/resources/migration/togetup-erd.sql
- src/main/resources/static/docs/index.html
- src/test/java/com/wakeUpTogetUp/togetUp/alarm/AlarmControllerTest.java
- ddl 수정
- mission, missionObject, alarm table 수정
- mission 테이블 분리에 따른 alarm api 수정
- 유저 알람 목록 가져오기 - 개인, 그룹
> #37 [FEAT] 미션 목록 가져오기, 알람 관련 api 개편

- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomDetailRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/model/RoomUser.java
- src/main/java/com/wakeUpTogetUp/togetUp/utils/TimeFormatter.java
- src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
- src/main/resources/static/docs/index.html
#56 
- 그룹 디테일 api 수정 : response 디자인에 맞추어 데이터 추가
- 그룹 참가 api 개발
> #56 [CHORE,FEAT] Feature/edit group 방 디테일 api 수정, 방 참가 api  개발

- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
- src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
- src/main/resources/static/docs/index.html
> #56 [FIX] : 방나가기 api 수정

- src/main/java/com/wakeUpTogetUp/togetUp/api/users/model/User.java
#작업
- user에서 null인 칼럼 기본값을 들어가게 수정
> [FIX] : user에서 null인 칼럼 기본값을 들어가게 수정

- .github/workflows/ci_dev.yml
- build.gradle
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/avatar/AvatarTheme.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
- src/main/resources/static/docs/index.html
- src/test/java/com/wakeUpTogetUp/togetUp/alarm/AlarmControllerTest.java
- ci_dev.yml 설정
- asciidoctor plugin이 deprecated되어 gradle 8.0 이상에서 빌드 안되는 에러 해결
spring rest docs를 현재 사용중이지 않고 build 시 directory가 없어 에러가 발생하는데, 해결하는데 시간이 걸릴 것 같아 주석처리하였습니다. 주요 기능 개발이 끝난 후에 다시 개발하겠습니다.
> #62 [ENV] Github action CI 환경설정

- src/main/resources/migration/data.sql
- src/main/resources/migration/mock.sql
- src/main/resources/migration/updates/20231014[avatar alarm user].sql
- src/main/resources/migration/updates/20231021[avatar userAvatar userAvatarPurchaseLog].sql
> resource/migration 폴더의 data.sql에서 updates 패키지로 db 수정사항 분리
파일 이름 컨벤션: 날짜[변경테이블1, 변경테이블2, ...]
> [ENV] DB schema 수정사항 기록 모음 패키지 updates 추가

- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
> 미션 판독 API의 이전으로 개발 기간 동안 임시 결과를 내려줌
#80
개발 완료 후 수정할 예정입니다.
> [FEAT] 미션 판독 API 결과를 임시로 변경

- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmProvider.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/response/AlarmSimpleRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/response/AlarmTimeLineRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/AlarmType.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionProvider.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationProvider.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserAvatarService.java
- src/main/java/com/wakeUpTogetUp/togetUp/utils/DateTimeProvider.java
- src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
- 미션 객체 이름을 한글로 응답
- 그룹/개인 알람 여부 정보 추가
- 기본 timezone을 Aisa/Seoul로 설정
closed : #86
> [FIX] 홈 - 알람 타임라인 API 응답 형식 수정

- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomDetailRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/utils/TimeFormatter.java
- `RoomService` - `getRoomDetail` 메소드 코드에 `timestampToDotDateFormat` 메소드 적용
- 미션 탐지 객체 디버그용 코드 추가
> [FIX] 알람 시간이 AM/PM으로 변환되지 않는 오류 수정

- src/main/java/com/wakeUpTogetUp/togetUp/api/auth/AuthController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/auth/apple/AppleJwtParser.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/auth/service/AppleLoginServiceImpl.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserController.java
- src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
- 스웨거 에러코드 설명 보충했습니다.
#42
- 유저컨트롤러에서 아바타 부분은 찬미님이 스웨거 설명 보충하면서 수정(리팩토링)하실 수도 있을 것 같아서 하지 않았습니다!
> [DOCS]  스웨거 명세서에 에러코드 설명 보충 

- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/home/HomeController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionProvider.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/response/GetMissionWithObjectListRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/ObjectDetectionService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserAvatarService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserController.java
- src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
- Error Response 명세서 작성
resolved : #42
> [DOCS] Error Response 명세서에 작성

- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserServiceHelper.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/fcmToken/FcmTokenRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/model/User.java
- fcm token 등록로직 변경, 리팩토링
- 유저조회와 유저가 없을 시 익셉션을 던지는 로직을 별도 클래스로 구현
- 수신 동의 설정 값 메소드 이름 변경
related : #96
> [REFACTOR,FIX] user 리팩토링

- src/main/java/com/wakeUpTogetUp/togetUp/api/dev/DevController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/dev/DevService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/MissionService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/dto/response/MissionCompleteRes.java
- 클라이언트에서 요청한 레벨업 직후 응답을 주는 api 구현했습니다.
- 해당 api는 클라이언트 디버깅 후 바로 폐기될 예정입니다.
> [FEAT] 개발용 미션 수행시 레벨업 응답 API 구현

- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/AlarmCreateReq.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomUserRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/request/RoomReq.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomDetailRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomInfoRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/AlarmMigrationMapper.java
- src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
- 그룹 아이콘, 미션아이콘, 알람아이콘이 미션 아이콘으로 통일됨에 따라 달라진 api를 수정했습니다.
- 알람생성을 버전에 맞게 하기 위해 AlarmMigrationMapper를 만들었습니다.
- 그룹, 그룹알람 생성 api 
-  그룹 리스트 api
-  그룹 디테일 보기 api
-  그룹 초대받았을 때 보이는 그룹 정보 api
-  그룹알람 만들면서 방에 참가하게 api 추가
related #101
> #101 [FIX,FEAT] 그룹,알람,미션 아이콘 통일로 인한 api 수정

- src/main/java/com/wakeUpTogetUp/togetUp/api/auth/LoginType.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/auth/apple/AppleClaimsValidator.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/auth/service/AppleLoginServiceImpl.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/auth/service/AuthService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationProvider.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/PushLogService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/entity/Notification.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/model/Room.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserAvatarService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/model/User.java
룸, 유저, 노티피케이션, auth의 code smell을 제거하였습니다. (주석, 사용안하는 코드)
related: #108 
user의 유저아바타서비스에 있는 주석, 유저 모델에 있는 주석도 제거하였는데 필요한 주석일 경우 댓글 날려주세요!
앞의 pr머지되면 main하고 머지한다음에 이 pr 머지하겠습니다.
> [CHORE] 룸, 유저, 노티피케이션, auth의 code smell 제거

- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmProvider.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/AlarmCreateReq.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/PatchAlarmReq.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/PostAlarmReq.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/response/GetAlarmRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/auth/AuthUserResolver.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/home/HomeController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserValidationService.java
- src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/AlarmMigrationMapper.java
- src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
- src/main/resources/migration/updates/20240406[alarm].sql
- 일회성 알람을 브리핑 보드에 반영하는 기능 구현
- 알람에서 사용하지 않는 기능인 다시울림 관련 필드 제거
- snooze_interval
- snooze_cnt
- is_snooze_activated
resolved : #100
> DB 변경사항이 있으니 병합 후 꼭 적용 바랍니다.
> [FEAT] 일회성 알람을 브리핑 보드에 반영하는 기능 구현

- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/model/Alarm.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/model/MissionLog.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/repository/MissionLogRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomQueryRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomQueryRepositoryImpl.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomQueryService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/UserCompleteType.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomDetailRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomInviteInfoRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomUserMissionLogRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/UserLogData.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/UserProfileData.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/model/Room.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/UserRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/utils/DateTimeProvider.java
- src/main/java/com/wakeUpTogetUp/togetUp/utils/TimeFormatter.java
- src/main/java/com/wakeUpTogetUp/togetUp/utils/mapper/EntityDtoMapper.java
- room에 cqrs패턴을 적용했습니다.
related  #106
- Criteria로는 조회모델을 커버하는데 한계가 있다고 느껴져 query Dsl을 공부 후 적용할지 고민입니다.
- 전체적으로 조회모델을 사용하는 도메인에서 사용하지 않는 도메인도 이용하다 보니 어색한 부분도 있는 것 같습니다.
단순한 조회는 JpaRepository를 상속받은 repository에 구현해도  되는데 
cqrs패턴에서는 권장하지 않아서 qeuryRepository에 jpql로 구현했습니다. 
- provider를 queryservice로 바꾸고 queryRepository를 만들었습니다. 
디스커션에서 여쭈어 보긴 했지만 query가 들어간 이름이 더 직관적이라고 생각해서 바꿨는데 
room에는 적절하지만 조회모델이 필요하지 않은 도메인에서는  provider라고 해도 될 것 같다는 생각도 들고, 
이름을 통일하는 것이 좋을 것 같다는 생각도 드네요.  
찬미님 의견이 궁금합니다.
> #106 [RESTRUCTURE] room에 cqrs 패턴 적용

- src/main/java/com/wakeUpTogetUp/togetUp/api/users/model/User.java
dev컨트롤러에서 유저를 가져오지 못하는 문제를 해결했습니다.
> [FIX] : 순환종속성으로 인한 무한재귀문제 해결

- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomUserMissionLogRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/UserProfileData.java
> [FIX] : dto 아바타 테마 설명 수정

- src/main/java/com/wakeUpTogetUp/togetUp/config/OpenApiConfig.java
도메인 변경사항 스웨거에 반영했습니다.
resolved : #123
> #123 [FIX] : 도메인 변경 스웨거에 반영

- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/AlarmValidationService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/dto/request/AlarmsDeactivateReq.java
- src/main/java/com/wakeUpTogetUp/togetUp/common/Status.java
alarm 일괄 비활성화 api를 구현했습니다.
앱이 꺼진 상태에서 울리는 일회성 알람의 경우 비활성화 처리가 어렵다는 클라이언트의 요청으로 앱 시작과 동시에 울리 알람을 일괄 비활성화를 지원하는 api를 구현했습니다.
> [FEAT] alarm 일괄 비활성화 api 구현

- src/main/java/com/wakeUpTogetUp/togetUp/api/auth/service/AppleLoginServiceImpl.java
> hotfix 애플 탈퇴 수정

- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/CustomDetectedObject.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/CustomDetectedTag.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/FaceAnnotationRecognitionResult.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/ObjectDetectionResult.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/VisionAnalysisResult.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/MissionService.java
- src/main/java/com/wakeUpTogetUp/togetUp/infra/azure/vision/AzureVision32Service.java
- src/main/java/com/wakeUpTogetUp/togetUp/infra/azure/vision/AzureVision40Service.java
- src/main/resources/migration/data.sql
- object detection 시에 target에 해당하는지에 대한 검사를 String.contains 메서드로 하다보니 target이 person인데, 사람이 찍히지 않아도 personal computer가 같이 촬영된 경우 단어에 person이 포함되어 미션이 성공해버리는 에러가 발생하였습니다.
- 정규 표현식을 사용하여 target 문자열 앞뒤로 공백이나 문자의 끝인 경우에 통과하도록 구현하였습니다.
- 판별 결과를 출력하는 메서드를 더욱 상세하게 출력하도록 리팩터링 했습니다.
related: #133
> [FIX] 객체 탐지 결과 도출 시 단어의 포함으로 성공하는 에러 해결

- .github/workflows/cicd_dev.yml
- src/main/java/com/wakeUpTogetUp/togetUp/config/OpenApiConfig.java
- 개발 환경 ci/cd 스크립트 작성하였습니다.
- swagger 요청 url을 수정하였습니다
- 운영서버 url 삭제
- 개발서버 url,로컬서버 url추가
resolved : #137 
aws 계정 정보와 ppk는 노션에 올려두었습니다.
> #137 개발 환경 ci/cd 추가, 스웨거 요청 url수정

- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/MissionService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/DataValueType.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationDataKeyType.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationDataValueType.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/NotificationService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/vo/AvatarUnlockedNotificationEvent.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/notification/vo/RoomMissionLogNotificationEvent.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/users/fcmToken/FcmTokenRepository.java
- 아바타 해금시 fcm noti 보내게 하였습니다. 
resolved : #143
> #143 [FEAT]  아바타 해금시 fcm noti 보내기

- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/FaceAnnotationRecognitionResult.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/ObjectDetectionResult.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/domain/VisionAnalysisResult.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/mission/service/MissionService.java
- src/main/resources/logback-spring.xml
미션 수행 기록을 mission.log에 로깅하는 기능을 구현했습니다.
로그 파일의 최대 용량은 10MB, 30개까지 보관(30일 보관), 최대 3GB까지 생성 가능으로 설정했는데 이에 대해 의견이 있으시다면 편하게 건의해주시면 좋을 것 같습니다!
> [FEATURE] 미션 수행 기록 별도 파일에 로깅

- src/main/java/com/wakeUpTogetUp/togetUp/api/alarm/repository/AlarmRepository.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomQueryRepositoryImpl.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomQueryService.java
-  roomlist 반환시 똑같은 room 여러개 반환하는 에러를 해결하였습니다.
- missionObject여러개 반환 해 NonUniqueResultException나는 에러 해결하였습니다.
> [FIX]: roomlist 에서 똑같은 room 여러개 반환하는 에러 해결, missionObject여러개 반환 해 NonUniqueResultException나는 에러 해결

- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
> [CHORE]: 그룹알람 생성 시 Id 반환하게 수정

- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomQueryService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomDetailRes.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomInviteInfoRes.java
- 클라이언트의 요청으로 RoomDetailRes, RoomInviteInfoRes에 미션 영어이름 추가했습니다.
> [CHORE]: RoomDetailRes, RoomInviteInfoRes에 미션 영어이름 추가

- src/main/java/com/wakeUpTogetUp/togetUp/infra/fcm/FcmService.java
- fcmService에서 노티를 보내는 함수를 수정하였습니다.
- fcmService에 google code style을 적용하였습니다.
resolved : #157 
코드 스타일을 적용한것과 수정한 것이 따로 커밋이 안되어 변경사항을 보기 어려운것 양해부탁드립니다!
코멘트에 언급해놓았습니다!
https://github.com/Wake-up-together-TogetUp/togetup-server/pull/158#discussion_r1738438762
> [FIX,STYLE]: deprecated된 메소드 수정 및 구글 코드 스타일 적용

- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomController.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/RoomService.java
- src/main/java/com/wakeUpTogetUp/togetUp/api/room/dto/response/RoomJoinRes.java
- 클라이언트의 요청으로 room에 들어갈 때 roomId도 응답에 추가하였습니다.
- 추가된 api
- room, alarm 만들기 api (처음 방을 만들 때 쓰는 api)
- room 들어가기 api 
- google code style적용으로 보기 어려운 점 양해부탁드립니다. 코멘트로 controller의 변경 부분 언급하겠습니다!
> [CHORE,STYLE]: room에 들어갈 때 roomId 응답에 추가

- .github/workflows/cicd_dev.yml
- .github/workflows/cicd_prod.yml
- Dockerfile
- docker-compose/docker-compose-dev.yml
- docker-compose/docker-compose-prod.yml
Gradle 캐싱을 통해 빌드 시간을 단축하고 Docker를 이용한 자동 배포 프로세스를 도입하였습니다.
1.  Docker 이미지 빌드 및 Push 자동화:
- **목표**: 기존 JAR 파일 배포에서 Docker 기반 배포로 전환해 더 안정적인 배포 환경을 구축합니다.
2. Docker Compose를 통한 자동 배포:
- **목표**: EC2 인스턴스에서 Docker Compose를 통해 애플리케이션 배포를 자동화하고 여러 컨테이너를 다루기 쉽게 합니다.
3. Gradle 캐싱 도입:
- **목표**: 빌드 시간 단축을 위해 불필요한 의존성 재다운로드를 방지합니다.
- Gradle 의존성과 Gradle Wrapper 파일을 캐싱하도록 설정했습니다.
related: #173 
- application-dev.yml, application-prod.yml 수정본 노션에 올려놨습니다.
- docker-compose.yml도 노션에 올려놨습니다. 
- 레포에도 올리는게 좋을지 의견 부탁드립니다.
- 테스트 db도 도커 컴포즈를 이용해 추후 띄울 예정입니다.
> #173 [ENV] : CI/CD 파이프라인 개선 - Docker 통합 및 Docker Compose 도입,  Gradle 캐싱
